CREATE VIEW VIEW_USER_INFORMATION AS
SELECT USER_INFO.*,EDUCATION.INSTITUTION_NAME,EDUCATION.PROGRAM_YEAR,
EDUCATION.PROGRAM_CONCENTRATION,EDUCATION.PROGRAM_DEGREE
FROM EDUCATION
INNER JOIN USER_INFO
ON USER_INFO.USER_ID = EDUCATION.USER_ID
ORDER BY USER_INFO.USER_ID;

CREATE VIEW VIEW_ARE_FRIENDS AS
SELECT * FROM FRIEND 
ORDER BY USER1_ID;

CREATE VIEW VIEW_TAG_INFORMATION AS
SELECT * FROM TAG;

CREATE VIEW VIEW_PHOTO_INFORMATION AS
SELECT ALBUM.*, PHOTO.*
FROM CONTAIN
	INNER JOIN PHOTO
		ON PHOTO.PHOTO_ID = CONTAIN.PHOTO_ID
	INNER JOIN ALBUM
		ON ALBUM.ALBUM_ID = CONTAIN.ALBUM_ID;

create view VIEW_EVENT_INFORMATION as
select *
from EVENT;
